# Generated by Django 5.2.3 on 2025-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbmls', models.CharField(max_length=11)),
                ('asignado', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('radicado', models.CharField(max_length=12)),
                ('dependencia', models.CharField(max_length=100)),
            ],
        ),
    ]
